/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hcIHmu4eMR0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button";
import Link from "next/link";
import React, { FC, ReactElement } from "react";

interface UnitProps {
  icon: ReactElement;
  title: string;
  description: string;
  buttonText: string;
  path: string;
}

export const Unit: FC<UnitProps> = ({
  icon,
  title,
  description,
  buttonText,
  path,
}) => {
  return (
    <div className="bg-white rounded-lg overflow-hidden shadow-md dark:bg-gray-950 dark:text-gray-50">
      {React.cloneElement(icon, {
        className: "w-full h-60 object-cover",
        height: 300,
        style: {
          aspectRatio: "400/300",
          objectFit: "cover",
        },
        width: 400,
      })}
      <div className="p-4 flex flex-col justify-between">
        <div>
          <h3 className="text-lg font-semibold">{title}</h3>
          <p className="text-gray-500 dark:text-gray-400 mt-2">{description}</p>
        </div>
        <div className="mt-4">
          <Link href={path}>
            <Button size="sm">{buttonText}</Button>
          </Link>
        </div>
      </div>
    </div>
  );
};
